### ISSUE TITLE
can this library be leveraged to talk to the controller alone?

### ISSUE THREAD

**Issue by EMCP** [cholcombe973/Juju#13]
I don't want to write charms in rust (yet) but want to do some basic monitoring of a controller and models.. seems this juju crate is more for if I am writing just charms.. correct?

any idea if this will easily support things similar to https://pypi.org/project/juju/ ?

**Comment by cholcombe973** [comment]
Yeah it was meant for writing charms. I needed a few components to make that work from what I remember. 

I can't really say for sure if it'll support what you're looking for because I haven't looked at juju in years. It's likely changed since I wrote this. 

It might be worth reaching out to the juju mailing list. However you probably won't get much help because rust isn't a supported language and they don't want to encourage anything other than Python.

**Comment by EMCP** [comment]
I hear you.. I think then for these few small things I will stick to using the referenced library above.. but am leaning hard into Rust and found your library.  thanks for answering

**Comment by cholcombe973** [comment]
Rust is a great language and I use it as my main one now. It's well worth learning
